# Generated by Django 4.2.22 on 2025-06-06 07:04

from django.db import migrations, models
import sync.models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted_record',
            name='sync_offline',
            field=models.BigIntegerField(default=sync.models.current_unix_ms),
        ),
        migrations.AddField(
            model_name='deleted_record',
            name='sync_online',
            field=models.BigIntegerField(default=sync.models.current_unix_ms),
        ),
    ]
