# Generated by Django 4.2.22 on 2025-06-08 07:17

from django.db import migrations, models
import sync.models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_deleted_record_sync_offline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_record',
            name='sync_online',
            field=models.BigIntegerField(default=sync.models.initial_sync_online),
        ),
    ]
