# Generated by Django 4.2.22 on 2025-06-08 07:20

from django.db import migrations, models
import sync.models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0003_alter_deleted_record_sync_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_record',
            name='sync_online',
            field=models.BigIntegerField(blank=True, default=sync.models.initial_sync_online, null=True),
        ),
    ]
