# Generated by Django 4.2.22 on 2025-06-08 09:55

from django.db import migrations, models
import sync.models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_alter_deleted_record_sync_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_record',
            name='model_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deleted_record',
            name='sync_offline',
            field=models.BigIntegerField(blank=True, default=sync.models.initial_sync_offline, null=True),
        ),
    ]
