# Generated by Django 4.2.22 on 2025-06-08 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_alter_deleted_record_model_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleted_record',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='deleted_record',
            constraint=models.UniqueConstraint(fields=('model_name', 'model_id'), name='unique_model_entry'),
        ),
    ]
