# Generated by Django 4.2.17 on 2025-06-10 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_alter_deleted_record_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deleted_record',
            name='sync_unix',
        ),
    ]
